[package]
name = "zeromq"
version = "0.3.3"
authors = ["Alexei Kornienko <alexei.kornienko@gmail.com>"]
edition = "2018"
description = "A native Rust implementation of ZeroMQ"
license = "MIT"
repository = "https://github.com/zeromq/zmq.rs"

[features]
default = ["tokio-runtime", "all-transport", "curvezmq"]
tokio-runtime = ["tokio", "tokio-util"]
async-std-runtime = ["async-std"]
all-transport = ["ipc-transport", "tcp-transport"]
ipc-transport = []
tcp-transport = []
curvezmq = ["crypto_box"]

[dependencies]
thiserror = "1"
futures = "0.3"
futures-util = "0.3"
pin-project-lite = "0.2"
async-trait = "0.1"
parking_lot = "0.11"
rand = "0.8"
bytes = "1"
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
num-traits = "0.2"
enum-primitive-derive = "0.2"
dashmap = "3.11"
crossbeam = "0.7"
uuid = { version = "0.8", features = ["v4"] }
regex = "1"
lazy_static = "1"
log = "0.4"
asynchronous-codec = "0.6"
async-std = { version = "1", features = ["attributes"], optional = true }
crypto_box = { version = "0.7.2", optional = true }

[dev-dependencies]
chrono = "0.4"
criterion = "0.3"
pretty_env_logger = "0.4"
zmq = "0.9"
hex = "0.4.3"


[lib]
bench = false

[[bench]]
name = "pub_sub"
harness = false
bench = false

[[bench]]
name = "req_rep"
harness = false
